dm_cli/bin/dm
dm_cli/enums.py
dm_cli/import_package.py
setup.py
tests/unit/test_import_package.py

- Support using dependencyAliases for types on disk
- Resolve these aliases upon import to DMSS
closes #15

feature: resolve dependencyAliases upon import

---

dm_cli/domain.py
dm_cli/import_package.py

- add "meta" as a part of the "Package" model
- meta data in a root package's package.json file was not uploaded
none

fix: meta data in package.json was not uploaded

---

dm_cli/domain.py
dm_cli/import_package.py
dm_cli/package_tree_from_zip.py
dm_cli/utils.py
setup.py
tests/unit/test_import_package.py

- Adds support for dotted references
NOTE: Had to introduce "parent" to the Package class. This is so we can resolve the path for each package, and get a context for the relative reference.
- It's handy
closes #11

feature: support for dotted (relative) references to types

---

dm_cli/bin/dm

add missing import
dm commands will fail
none

chore: fix ApiException import

---

dm_cli/utils.py
setup.py
tests/unit/test_import_package.py

- Fixes a bug where references with a full/absolute format were replaced by "null"
Should be allowed to import files containing full references
closes #53

fix: full references were replaced by null

---

dm_cli/bin/dm
dm_cli/utils.py

wrap functions in the dmss exception wrapper function to avoid duplicate error handling.
closes #70

feat: use exception wrapper in cli commands

---

.github/workflows/tests.yaml
dm_cli/__init__.py
dm_cli/command_group/data_source.py
dm_cli/command_group/entities.py
tests/integration/docker-compose.yaml
tests/test_data/more_documents/bmw.json
tests/test_data/more_documents/engines/engineA.json
tests/test_data/more_documents/engines/engineB.json
tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/recipe_links/Engine.json
tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/recipe_links/car.json

test more dm cli commands
closes #83

test: test more CLI commands

---

dm_cli/__init__.py
dm_cli/domain.py
dm_cli/import_entity.py
dm_cli/package_tree_from_zip.py
dm_cli/utils/reference.py
tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/instances/package.json
tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/Car.json
tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/EnginePackage/package.json
tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/package.json
tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/package.json
tests/unit/test_import_entity.py
tests/unit/test_import_package.py

* Update to use new Reference blueprint
* Replace relative references in meta for packages

fix: replace references in meta

---

dm_cli/domain.py
dm_cli/import_entity.py
dm_cli/utils/utils.py

* Add $ to mark references as ID references

refactor: set correct format for id references

---

dm_cli/__init__.py

chore: bump version

---

dm_cli/command_group/data_source.py
dm_cli/command_group/entities.py
dm_cli/dmss_api/api/default_api.py
dm_cli/dmss_api/api/document_api.py
dm_cli/dmss_api/model/pat_data.py
dm_cli/import_entity.py
dm_cli/import_package.py
dm_cli/utils/utils.py

* Update add and remove endpoints

refactor: update add and remove endpoints

---

dm_cli/command_group/data_source.py

* Avoid importing data sources twice

fix: data sources imported twice

---

dev-requirements.txt
requirements.txt

chore: upgrade dependencies

---

dm_cli/bin/dm
dm_cli/command_group/data_source.py
dm_cli/command_group/entities.py

Update documentation for cli commands. Uses the Annoted class to get nice formatting in the terminal:
https://github.com/equinor/dm-docs/issues/35

docs: update documentation for cli commands

---

dm_cli/dmss_api/model_utils.py

Temporary fix for OpenApi bug turning ints into floats
Closes #565

fix: temporary fix for OpenApi type conversion error

---

generate-dmss-api.sh

chore: fix api generator scope

---

dm_cli/bin/dm
dm_cli/command_group/data_source.py
dm_cli/import_entity.py
dm_cli/import_package.py
dm_cli/utils/resolve_local_ids.py
tests/unit/resolve_local_ids_test_data/carRentalCompany.final.json
tests/unit/resolve_local_ids_test_data/carRentalCompany.json
tests/unit/test_resolve_local_ids.py

Resolves local ids found in documents before upload
Allows for documents with local ids to be uploaded
Closes #131

feat: resolve local id

---

dm_cli/utils/reference.py

* Resolve enum type paths on disk!

feat: resolve enum type

---

dm_cli/utils/reference.py

* Ignore resolve references that start with ~

fix: ignore tilde symbol

---

dm_cli/utils/reference.py

* Reset app scripts fails in example app due to wrong resolving of files on disk.

fix: resolve global files on disk

---

dm_cli/utils/reference.py
tests/integration/docker-compose.yaml
tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/instances/data/simulation.json

* fix: how we find the data folder

fix: relative storage references

---

dm_cli/command_group/entities.py

CI is flaky because Radix returns Bad Gateway on validation.
Add retry on validation should help

fix: validate request should be retried for more robustness

---

dm_cli/command_group/entities.py
dm_cli/utils/reference.py

No point in retrying the validation request if the data is not valid.

feat: dont retry request on a validation error

---

README.md
dm_cli/bin/dm
dm_cli/command_group/data_source.py
dm_cli/command_group/entities.py

part of https://github.com/equinor/dm-docs/issues/48

docs: README to be up-to-date

---

.github/workflows/tests.yaml
LICENSE
dev-requirements.txt

* Add licence
* Meet Equinor repository requirements

docs: add MIT licence
