dm_cli/application.py, setup.py
fix typing syntax to support py3.8
if using python3.8 the dm-cli gives error
closes #20
=> fix: change return types in application.py functions

dm_cli/bin/dm, setup.py, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/instances/demoApplication.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/instances/package.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/Car.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/Wheel.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/DemoApplication.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/package.json, tests/test_data/test_app_dir_struct/data_sources/DemoApplicationDataSource.json
- Print error message and exit on failed package import (no more stack traces)
- Added a test "app" directory
The import would fail with no feedback
none
=> fix: print error message and exit on failed import

dm_cli/import_package.py, setup.py
reset command no longer fails on empty object.
The example entity failed before: because "input" attribute is empty
bug fix
=> fix: replace_relative_references no longer fails on empty objects

dm_cli/bin/dm, dm_cli/import_package.py, setup.py, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/Car.json, tests/unit/test_import_package.py
- Read "_meta_" from all entities, not just root packages
- Will not allow multiple dependencies with the same alias if the values are different
- The user might define some dependencies further down the "tree"
none
=> feature: respect meta data defined in entities

.pre-commit-config.yaml, README.md, dm_cli/application.py, dm_cli/bin/dm, dm_cli/domain.py, dm_cli/import_package.py, dm_cli/package_tree_from_zip.py, dm_cli/utils.py, setup.py, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/Car.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/ExtendsRelative.json, tests/unit/test_import_package.py
- support _cross package relative references_
- added documentation on supported reference formats
- added "\_blueprintPath\_" as a keyword for values to resolve
- use the "black" profile for isort pre-commit hook to avoid conflicts with black
- set black line width to 119
REGRESSION: We can no longer use "_id" placeholders for entity id's. _id is not handled in any special way, and need to be "correct" on disk.
closes #40
=> feature: support cross data source relative references

README.md, dm_cli/import_package.py, dm_cli/package_tree_from_zip.py, setup.py, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/EnginePackage/Engine.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/EnginePackage/package.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/package.json
update add_file_to_package function to add meta info to package (and don't upload pacakge.json files to dmss)
the package.json file is used for loading meta information to a package when importing a package. Before, this package.json file was interpreted as an entity by mistake (see also issue details).
closes #32
=> fix: do not include package.json as an entity in a package

dm_cli/import_package.py
- Resolves a bug where the `attributeType` attribute of a document was replaced with an incorrect relative reference for `primitive types` such as `string`, leading to e.g. `attributeType: 'dmss://DemoApplicationDataSource/models/string'`
- To resolve a bug
N/A
=> fix: do not replace references for primitives

dm_cli/enums.py, dm_cli/utils.py, setup.py
fix bug with object type
when using "object" for attribute type, the value is translated to a path when running the dm-cli reset command.
=> fix: bug with object type in  replace_relative_references()

README.md, dm_cli/__init__.py, dm_cli/import_entity.py, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/instances/demoApplication.json
- Grabs "meta" from remote target and merge with meta from the entity on "single entity upload"
- Sane default behavior
closes #61
=> feature: import single entity and use remote meta

.pre-commit-config.yaml, dm_cli/dmss.py, dm_cli/utils.py
- Dont modify keyword "_default_" during import
- "_default_" was interpreted as as reference. When in fact it's a special keyword that should be kept
closes #66
=> fix: dont try to resolve '_default_' blueprintPath

.github/workflows/on-main-push.yaml
- Remove "publish" workflow call in ""push-to-main"
- Should only be one trigger for "publish"(on-tag)
none
=> ci: don't call publish on push to main

README.md, dm_cli/__init__.py, dm_cli/bin/dm
- Adds a shorthand command for importing blueprints from plugins
- Simplify importing blueprints from plugins
closes #64
=> feature: added shorthand command for plugin blueprints

.github/CODEOWNERS, .github/workflows/tests.yaml, MANIFEST.in, tests/integration/docker-compose.yaml
- Install dm-cli from the same ".tar.gz" bundle used when installing from pipy when running integration tests
- Test that the "to-be-published" package actually works
closes #80
=> tests: run integration tests with build pipy-package

dm_cli/domain.py, dm_cli/utils/utils.py
fix bug with converting Package class object to dict. 
Update the way the content list of a package is generated as JSON, to be compatible with the new reference scheme
closes #81 
https://github.com/equinor/data-modelling-storage-service/pull/397 must be merged before tests pass
=> fix: bug with generate package content dict

.github/workflows/tests.yaml, dm_cli/__init__.py, dm_cli/bin/dm, dm_cli/dmss_api/api/default_api.py, dm_cli/dmss_api/api/document_api.py, dm_cli/dmss_api/api/lookup_table_api.py, dm_cli/dmss_api/model/pat_data.py, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/more_recipe_links/wheel.json
add functionality to create lookup table from several paths into a single app. The generated dmss api is also updated
closes #90 assumed that https://github.com/equinor/data-modelling-storage-service/pull/428 has been merged
=> feat: create lookup table from several paths

tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/Car.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/EnginePackage/Engine.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/CarPackage/Wheel.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/DemoApplication.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/ExtendsRelative.json, tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/models/ExternalFile.json
remove uiRecipes from blueprints, that should not be included. This attribute is not specified in CORE:Blueprint
=> fix: remove uiRecipes from blueprints

dm_cli/command_group/data_source.py, dm_cli/enums.py, dm_cli/import_entity.py, dm_cli/import_package.py, dm_cli/utils/reference.py
To be able to upload the core blueprints in DMSS needed to make two changes:
1. When dm reset app is called, it will not use the add document endpoint for adding packages, but instead just upload the using the document raw endpoint.
2. Don't try to replace_relative_references of the attribute type any (e.g. to replace the relative address to files on disk). The any type is used in the DMSS core blueprints.
=> feat: be able to upload DMSS blueprints

dm_cli/dmss.py, dm_cli/import_entity.py, dm_cli/import_package.py, generate-dmss-api.sh, requirements.txt
- Adds "Tenacity's" retry decorator for some of the functions communicating with DMSS
Tenacity: https://tenacity.readthedocs.io/en/latest/
- CI fails to reset DMSS once in a while.
closes #146
=> feat: retry requests on network errors

dm_cli/command_group/data_source.py, dm_cli/import_entity.py, dm_cli/import_package.py, dm_cli/package_tree_from_zip.py, dm_cli/utils/reference.py
- Remove zip file for global folder
- Resolve storage references and locate them directly from disk when uploading global files
Global folder is only zipped if defined in the data source. It should be possible to upload files just by knowing their location on disk.
=> fix: resolve storage references on disk

.github/workflows/tests.yaml, dm_cli/bin/dm, dm_cli/command_group/data_source.py, dm_cli/command_group/entities.py, dm_cli/import_entity.py, dm_cli/import_package.py, dm_cli/utils/utils.py
- fix: _meta_ might not exist in every package.json
- feat: option to validate plugin blueprints
- feat: option to validate on 'entity' command + separate validate command
Validation was only available for "reset app".
=> feature: validation on single entity upload

dm_cli/bin/dm, dm_cli/command_group/entities.py, dm_cli/enums.py, dm_cli/import_entity.py, dm_cli/import_package.py, dm_cli/package_tree_from_zip.py, dm_cli/utils/reference.py, dm_cli/utils/utils.py, tests/integration/docker-compose.yaml, tests/unit/test_import_package.py, tests/unit/test_replace_references.py
- Refactor `replace_relative_references()` to check type of dict before replacing
- This also made it simpler, faster, and more robust
- Added a few more cases to the tests
- Upgrade DMSS version used in tests
- dm-cli exit with 1 on validation error, halting  any scripts with "set -e"
see #145 
closes #145
=> feat: check context before replacing type references

dm_cli/command_group/data_source.py, dm_cli/command_group/entities.py, dm_cli/dmss.py, dm_cli/import_entity.py, dm_cli/import_package.py
Fix a bug where the filename was used to determine remote target for validation. This does not work, as the file name can not be determined, and will definitely not have a .json ending.
closes #172
=> fix: validate single entities before upload
